### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by tacman** [PacktPublishing/Unity-2020-Virtual-Reality-Projects-3rd-Edition-#1]
Trying to get something, anything, to work with my new Oculus Quest 2.  I've read the first half of the book (quite enjoying it!), but I can't seem to get any of the examples to work, using either 2020 or 2019.  For example:

Assets\_UWVRP3Assets\Chapter11\Scripts\RenderCubemapWizard.cs(5,36): error CS0246: The type or namespace name 'ScriptableWizard' could not be found (are you missing a using directive or an assembly reference?)

Can you point me in the right direction?  I know VR is constantly evolving, Unity and Oculus are pretty dynamic, but would love to get something working.  I don't think the problem is the new Quest, but rather the way newer versions of Unity handle namespaces.

**Comment by linojon** [comment]
Hello. Thank you for reporting this error. I have pushed a fix to the repository. 

The problem was the file RenderCubemapWizard.cs is a Unity Editor script so it must be in a folder named "Editor". This file was a last minute addition and we missed that it gives an error when you build. 

Alternatively you could just delete that script from your project as its an example taken mostly from the Unity Manual here (https://docs.unity3d.com/ScriptReference/Camera.RenderToCubemap.html)

Best to you and many virtual successes :)

**Comment by tacman** [comment]
Thanks.  Now I'm getting

ImportFBX Errors:
Couldn't read file
/home/tac/g/tacman/Unity-2020-Virtual-Reality-Projects-3rd-Edition-/UVRP3Projects/Assets/ANGRY
MESH/Snowman/Sources/Meshes/Snowman.FBX.
Unexpected file type

It goes away after I install the Snowman Asset.  But something's still not
quite right.  I'll report back after I've played around some more.

This repo is really large.  I'm in rural Virginia, on a very slow internet
connection, so cloning this repo took more than an hour.  Perhaps another
iteration could use the github large file storage?

**Comment by linojon** [comment]
Ok. Maybe you didn't realize the repo has two main folders. The Projects one is large and is a Unity project with -completed- scenes for each book chapter. The Files folder is just the Assets you can use to -begin- each chapter. You don't need to clone the whole thing you can just download what you need.

**Comment by linojon** [comment]
Make sure you have Git LFS installed and when you are cloning or pulling the repository it has successfully downloaded all the LFS (large files) types identified in the .gitattributes file. See https://github.com/git-lfs/git-lfs/wiki/Installation
